server:
    port: 8080
 
zuul:
    prefix: /api
    routes:
        users:
            path: /users/**
            serviceId: budget-manager-rest
            
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:8761}/eureka/